# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AJCountryPickerDemo' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# Pods for AJCountryPickerDemo
pod 'AJCountryPicker', :git => 'https://github.com/techmehra/AJCountryPicker.git'
target 'AJCountryPickerDemoTests' do
inherit! :search_paths
# Pods for testing
end

end
